apiVersion: v1
type: postrenderer/v1
name: label-injector
version: v1.0.7
runtime: subprocess
runtimeConfig:
  platformCommand:
  - command: java
    args:
    - -jar
    - ${HELM_PLUGIN_DIR}/vault-crd-helm-renderer.jar
  install:
    - command: curl
      args:
      - -L
      - -o
      - ${HELM_PLUGIN_DIR}/vault-crd-helm-renderer.jar
      - https://github.com/DaspawnW/vault-crd-helm-renderer/releases/download/v1.0.7/vault-crd-helm-renderer.jar